coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 60
        threshold: 1%
        base: auto
        branches:
          - main
          - master
    patch:
      default:
        target: 60
        threshold: 1%

ignore:
  - "tests/"
  - "venv/"
  - ".venv/"
  - "*/__pycache__/"
